import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";
import { Header } from "./components/header/header";
import { clsx } from "clsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layoutClassName = clsx(styles.layoutWrapper, inter.className);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={layoutClassName}>
        <Header />
        {children}
      </body>
    </html>
  );
}
