import { GoogleSignInButton } from "@/app/components/google-sign-in-button";
import { SignOut } from "@/app/components/sign-out-button";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Weather App Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
