import { GoogleSignInButton } from "@/app/ui/GoogleSignInButton";
import { SignOut } from "@/app/ui/SignOut";
import { Sign } from "crypto";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Weather App Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div>
        <GoogleSignInButton />
        <SignOut />
      </div>
      {children}
    </main>
  );
}
